# -*- coding: utf-8 -*-
# Copyright (c) 2016 Ecreall — Copyright (c) 2026 Logikascium
# Licensed under the GNU Affero General Public License v3 or later.
"""HTML views and the two legacy-compatible entry points.

Compatibility contract with the 2016 service, kept deliberately:

* `GET /?url=<target>` answers JSON
  `{"short_url": ..., "code": "SUCCESS", "original_url": ...}`,
  and on refusal `{"code": "ERROR", "error": ..., "original_url": ...}`;
* `POST /` with a form field `url` answers the HTML page carrying the
  short link;
* `GET /<code>` answers 302 to the target.

One documented change: an unknown code answers **404** instead of the
old 200-with-an-error-page. A monitor could not previously tell a dead
link from a working one.
"""
from __future__ import annotations

import logging
from urllib.parse import urlsplit

from pyramid.httpexceptions import HTTPFound, HTTPNotFound, HTTPSeeOther
from pyramid.interfaces import IRoutesMapper
from pyramid.view import notfound_view_config, view_config

from .constants_and_globals import (
    AVAILABLE_LANGUAGES,
    LANGUAGE_NAMES,
    LOCALE_COOKIE,
    LOCALE_COOKIE_MAX_AGE,
    _,
)
from .services import CodeExhausted, count_links, create_link, find_by_code, record_hit
from .urlvalidation import InvalidURL, to_wire_url

log = logging.getLogger(__name__)

#: Message shown for each refusal reason. The keys are the `msgid`
#: values raised by `urlvalidation`, so a new refusal reason without a
#: message here fails `tests/test_i18n.py`.
ERROR_MESSAGES = {
    "error_url_required": _("error_url_required", default="Enter a web address to shorten."),
    "error_url_too_long": _("error_url_too_long", default="That address is too long."),
    "error_url_scheme": _(
        "error_url_scheme", default="Only http:// and https:// addresses can be shortened."
    ),
    "error_url_host": _("error_url_host", default="That address has no usable host name."),
    "error_url_port": _("error_url_port", default="That address has an invalid port number."),
    "error_url_credentials": _(
        "error_url_credentials",
        default="Addresses carrying a user name and password are not accepted.",
    ),
    "error_url_private": _(
        "error_url_private", default="That address points to a private network."
    ),
    "error_url_blocked": _("error_url_blocked", default="That host is not accepted."),
    "error_url_control_characters": _(
        "error_url_control_characters", default="That address contains invalid characters."
    ),
    "error_code_exhausted": _(
        "error_code_exhausted", default="No short code is available. Contact the administrator."
    ),
    "error_body_too_large": _(
        "error_body_too_large", default="That request is too large."
    ),
    "error_cross_site": _(
        "error_cross_site",
        default="This form cannot be submitted from another website.",
    ),
    "error_rate_limited": _(
        "error_rate_limited", default="Too many links created from here. Try again shortly."
    ),
}


#: Routes the language switcher is allowed to send a visitor back to.
#:
#: EXTERNAL AUDIT 2026-08-22, finding C-01. The previous guard filtered
#: the STRING: it accepted anything starting with '/' that did not start
#: with '//'. That let `/\evil.example` through, and the URL Standard
#: requires a browser to read a backslash as a separator for http(s):
#:
#:     new URL('/\evil.example', 'https://good.example/x')
#:       -> https://evil.example/
#:
#: An open redirect on our own domain, which is precisely the domain a
#: phishing page wants to be seen leaving from.
#:
#: Filtering strings for this is a losing game -- there is always one
#: more spelling. So the parameter is no longer echoed at all: it is
#: MATCHED against a named route, and the location we answer with is
#: REGENERATED by Pyramid from that route's name. Whatever the visitor
#: sends, the answer can only ever be a URL this application knows how
#: to build.
#:
#: `redirect` is deliberately absent: it matches `/{code}` -- that is,
#: everything -- and sending someone "back" to a short link after a
#: language change would walk them straight off the site.
#:
#: Adding a page means adding its route name here, and
#: `tests/test_audit_external_20260822.py` fails on a route that is
#: neither allowed nor explicitly excluded.
RETURNABLE_ROUTES = frozenset({"home"})

#: Route names that must never be a return destination, with the reason.
#: Listed rather than merely omitted, so the next person adding a route
#: makes a decision instead of inheriting a default.
NON_RETURNABLE_ROUTES = {
    "redirect": "matches every path and leaves the site",
    "set_locale": "the switcher itself; returning to it would loop",
    "healthz": "not a page",
    "api_shorten": "not a page",
    "api_link": "not a page",
    # Registered by add_static_view, not by routes.py; it serves the
    # stylesheet and the script, never a page.
    "__static/": "static assets, not a page",
}


def safe_return_path(request, came_from):
    """Resolve `came_from` to a path of THIS application, or home.

    The returned value never contains a character the caller supplied:
    it is built by `route_path` from a matched route name and its
    matched elements.
    """
    default = request.route_path("home")
    if not came_from:
        return default
    # A local path has no scheme and no authority. Checked before
    # anything else so `https://evil.test/`, `//evil.test/` and
    # `javascript:...` are gone at the first step.
    try:
        parts = urlsplit(came_from)
    except ValueError:
        return default
    if parts.scheme or parts.netloc or not parts.path.startswith("/"):
        return default

    mapper = request.registry.queryUtility(IRoutesMapper)
    if mapper is None:
        return default
    for route in mapper.get_routes():
        if route.name not in RETURNABLE_ROUTES:
            continue
        matched = route.match(parts.path)
        if matched is not None:
            return request.route_path(route.name, **matched)
    return default


def _page_context(request, with_count=True, **extra):
    """Values every rendering of the page needs.

    `with_count` exists for the 404 page. AUDIT 2026-08-22, finding
    S-09: counting the links on every unknown path meant a scan of the
    short-code space -- exactly what an enumerator does -- charged the
    database one aggregate per miss, and made the 404 handler itself
    fail when the database was unavailable.
    """
    context = {
        "settings": request.app_settings,
        "languages": [(code, LANGUAGE_NAMES[code]) for code in AVAILABLE_LANGUAGES],
        "current_locale": request.locale_name,
        "link_count": count_links(request.dbsession) if with_count else None,
        "submitted_url": "",
        "short_url": None,
        "short_base": request.app_settings.base_url,
        "short_code": None,
        "error": None,
        "already_existed": False,
    }
    context.update(extra)
    return context


def _mark_deprecated(request) -> None:
    """Say, in the answer itself, that this entry point is on its way out.

    `Deprecation: true` and a `Link` to the successor are what a client
    library can notice without anyone reading a changelog.
    """
    request.response.headers["Deprecation"] = "true"
    request.response.headers["Link"] = (
        '<%sapi/v1/shorten>; rel="successor-version"' % request.app_settings.base_url
    )


#: `Sec-Fetch-Site` values a creation may arrive with.
#:
#: EXTERNAL AUDIT, second pass, finding D-02. A `POST` in
#: `application/x-www-form-urlencoded` is a CORS-SIMPLE request: the
#: browser sends it with no preflight and shows the answer to nobody.
#: So any third-party page could make its visitors create links —
#: at THEIR address, which also spreads the rate limit across
#: strangers — and the preflight added in train 0009 stood in front of
#: none of it, because a form never preflights.
#:
#: There is no session here, so there is no CSRF token to check.
#: `Sec-Fetch-Site` is the sessionless answer: the browser states where
#: the request came from, and a page cannot forge it.
#:
#: `none` is a typed address or a bookmark. `same-origin` is our own
#: form. `same-site` covers a sibling host of the same registrable
#: domain, which for a service mounted under a coop's domain is a
#: legitimate caller.
ALLOWED_FETCH_SITES = frozenset({"none", "same-origin", "same-site"})


def cross_site_creation(request) -> bool:
    """True when a form creation arrives from another site.

    Fail-OPEN when the header is absent: `curl`, an old browser and
    every non-browser client send nothing, and refusing them would
    break far more than it protects. The header exists in every current
    browser, which is exactly where the attack lives — a page can
    neither remove it nor choose its value.
    """
    site = request.headers.get("Sec-Fetch-Site")
    if not site:
        return False
    return site.strip().lower() not in ALLOWED_FETCH_SITES


def body_too_large(request) -> bool:
    """True when the declared request body exceeds `max_body_bytes`.

    Read from `Content-Length`, NOT by measuring `request.body`:
    reading a body in order to discover that it is too big IS the
    denial of service (external audit C-04). A request that declares no
    length -- chunked transfer -- is let through here and stopped by
    the server's own `max_request_body_size`, which carries the same
    number.
    """
    limit = request.app_settings.max_body_bytes
    if limit <= 0:
        return False
    declared = request.content_length
    return declared is not None and declared > limit


def _client_key(request) -> str:
    """Throttling key. `client_addr` honours the trusted-proxy config."""
    return request.client_addr or "unknown"


@view_config(route_name="home", request_method="GET", renderer="templates/home.pt")
def home(request):
    """The form, or -- when `?url=` is present -- the legacy JSON reply."""
    raw_url = request.params.get("url")
    if raw_url is not None:
        return _legacy_get_json(request, raw_url)
    return _page_context(request)


def _legacy_get_json(request, raw_url):
    """`GET /?url=...` -- the 2016 JSON shape, character for character.

    Kept because KuneAgi calls it and the first promise of this project
    is that nothing written against the 2016 service breaks. Every
    answer carries `Deprecation` and a `Link` to the successor, and
    every USE is logged at INFO -- the only way to find out whether the
    callers have actually moved before switching it off.
    """
    request.override_renderer = "json"
    settings = request.app_settings

    if not settings.enable_legacy_get:
        # 410 rather than 404: the endpoint existed, the answer is that
        # it is over. The 2016 body shape is preserved so an old
        # client's parser reads the refusal instead of choking on it.
        log.info("legacy GET /?url= refused: disabled by configuration")
        request.response.status_int = 410
        _mark_deprecated(request)
        return {
            "code": "ERROR",
            "error": "error_legacy_get_disabled",
            "original_url": raw_url,
        }

    # One line per use, deliberately. The target is NOT logged: it is
    # already in the query string of the access log, and repeating it
    # here would put it in a second place for no gain.
    log.info(
        "legacy GET /?url= used (referer=%r) — the successor is "
        "POST /api/v1/shorten",
        request.headers.get("Referer", ""),
    )
    _mark_deprecated(request)

    if not request.throttle.allow(_client_key(request)):
        request.response.status_int = 429
        return {
            "code": "ERROR",
            "error": "rate limited",
            "original_url": raw_url,
        }
    try:
        link, _created = create_link(request.dbsession, raw_url, request.app_settings)
    except InvalidURL as invalid:
        request.response.status_int = 400
        return {
            "code": "ERROR",
            "error": invalid.msgid,
            "original_url": raw_url,
        }
    except CodeExhausted:
        log.error("code space exhausted at length %d", request.app_settings.code_length)
        request.response.status_int = 503
        return {
            "code": "ERROR",
            "error": "error_code_exhausted",
            "original_url": raw_url,
        }
    return {
        "short_url": request.app_settings.short_url(link.code),
        "code": "SUCCESS",
        "original_url": link.url,
    }


@view_config(route_name="home", request_method="POST", renderer="templates/home.pt")
def shorten_form(request):
    """`POST /` from the page's own form."""
    if cross_site_creation(request):
        request.response.status_int = 403
        return _page_context(request, error=ERROR_MESSAGES["error_cross_site"])
    # Before `request.POST` parses anything.
    if body_too_large(request):
        request.response.status_int = 413
        return _page_context(request, error=ERROR_MESSAGES["error_body_too_large"])
    raw_url = request.POST.get("url", "")
    if not request.throttle.allow(_client_key(request)):
        request.response.status_int = 429
        return _page_context(
            request, submitted_url=raw_url, error=ERROR_MESSAGES["error_rate_limited"]
        )
    try:
        link, created = create_link(request.dbsession, raw_url, request.app_settings)
    except InvalidURL as invalid:
        request.response.status_int = 400
        return _page_context(
            request,
            submitted_url=raw_url,
            error=ERROR_MESSAGES.get(invalid.msgid, ERROR_MESSAGES["error_url_required"]),
        )
    except CodeExhausted:
        log.error("code space exhausted at length %d", request.app_settings.code_length)
        request.response.status_int = 503
        return _page_context(
            request, submitted_url=raw_url, error=ERROR_MESSAGES["error_code_exhausted"]
        )
    return _page_context(
        request,
        submitted_url=link.url,
        short_url=request.app_settings.short_url(link.code),
        short_code=link.code,
        already_existed=not created,
    )


@view_config(route_name="redirect", request_method=("GET", "HEAD"))
def redirect(request):
    """`GET /<code>` -- the whole point of the service."""
    code = request.matchdict["code"]
    link = find_by_code(request.dbsession, code)
    if link is None:
        raise HTTPNotFound()
    record_hit(request.dbsession, link, request.app_settings)
    # to_wire_url even though creation already stored a wire-safe form:
    # the rows imported verbatim from the 2016 database never went
    # through it, and one of them carrying a non-ASCII character would
    # otherwise 500 on every single visit (audit finding S-01).
    response = HTTPFound(location=to_wire_url(link.url))
    # Do not leak the short link (and therefore the visitor's path) to
    # the destination site.
    response.headers["Referrer-Policy"] = "no-referrer"
    # A short link is permanent in fact but not in law: keep it
    # revocable by telling caches not to keep the redirect.
    response.headers["Cache-Control"] = "no-store"
    return response


@view_config(route_name="set_locale")
def set_locale(request):
    """Remember an explicit language choice and return where we came from."""
    locale = request.matchdict.get("locale")
    response = HTTPSeeOther(
        location=safe_return_path(request, request.params.get("came_from"))
    )
    if locale in AVAILABLE_LANGUAGES:
        response.set_cookie(
            LOCALE_COOKIE,
            value=locale,
            max_age=LOCALE_COOKIE_MAX_AGE,
            httponly=True,
            samesite="Lax",
            secure=request.scheme == "https",
        )
    return response


@view_config(route_name="healthz", renderer="json")
def healthz(request):
    """Liveness plus a real database round-trip, for the container check."""
    from sqlalchemy import text

    request.dbsession.execute(text("SELECT 1"))
    return {"status": "ok", "links": count_links(request.dbsession)}


@notfound_view_config(renderer="templates/notfound.pt")
def notfound(request):
    """Unknown code, or unknown path. 404 either way."""
    request.response.status_int = 404
    return _page_context(request, with_count=False)
